// Shared team data for index and profile pages
const teamMembers = [
    {
        name: "Hafsa",
        age: 25,
        location_birth: "Casablanca, Morocco",
        flag: "🇲🇦",
        role: "Data Engineer",
        image: "images/hafsa.png",
        biggest_achivement: "Developed a real-time data processing pipeline using Apache Kafka.",
        skills: ["Node.js", "Python", "MongoDB"],
        weaknesses: ["Public Speaking", "Time Management"],
        funfact: "Loves hiking and has climbed several mountains in Corsica.",
        contact: "hafsa@equipe.com",
        group: "data"
    },
    {
        name: "Abdou",
        age: 28,
        location_birth: "Dakar, Senegal",
        flag: "🇸🇳",
        role: "UI/UX Designer",
        image: "images/abdou.png",
        biggest_achivement: "Redesigned the mobile app interface, leading to a 30% increase in user engagement.",
        skills: ["Figma", "Adobe XD", "Design Thinking", "Prototypage", "Animation"],
        weaknesses: ["Overthinking", "Perfectionism"],
        funfact: "Enjoys playing the djembe and has performed at local festivals.",
        contact: "abdou@equipe.com",
        group: "design"
    },
    {
        name: "Achille",
        age: 22,
        location_birth: "Bastia, France",
        flag: "🇫🇷",
        role: "Project Manager",
        image: "images/achille.png",
        skills: ["Agile", "Scrum", "Team Management", "Planning", "Communication"],
        biggest_achivement: "Delivered a cross-functional platform migration on time and under budget.",
        weaknesses: ["Delegation", "Overcommitting"],
        funfact: "Used to be a semi-pro futsal goalkeeper.",
        contact: "achille@equipe.com",
        group: "management"
    },
    {
        name: "Ahmed",
        age: 26,
        location_birth: "Rabat, Morocco",
        flag: "🇲🇦",
        role: "Data Scientist",
        image: "images/ahmed.png",
        skills: ["Python", "Machine Learning", "SQL", "Tableau", "TensorFlow"],
        biggest_achivement: "Won a Kaggle competition top-3 medal for a NLP challenge.",
        weaknesses: ["Design systems", "Long meetings"],
        funfact: "Can solve a Rubik's cube in under 40 seconds.",
        contact: "ahmed@equipe.com",
        group: "data"
    },
    {
        name: "Ambroise",
        age: 27,
        location_birth: "Lyon, France",
        flag: "🇫🇷",
        role: "Backend Developer",
        image: "images/ambroise.png",
        skills: ["Java", "Spring Boot", "Docker", "Kubernetes", "AWS"],
        biggest_achivement: "Designed a high throughput API handling 50k req/min.",
        weaknesses: ["UI work", "Writing documentation"],
        funfact: "Brews specialty coffee and built a home roasting setup.",
        contact: "ambroise@equipe.com",
        group: "dev"
    },
    {
        name: "Anthony",
        age: 24,
        location_birth: "Nice, France",
        flag: "🇫🇷",
        role: "Mobile Developer",
        image: "images/antho.png",
        skills: ["React Native", "Flutter", "Swift", "Kotlin", "Firebase"],
        biggest_achivement: "Published a cross-platform app reaching 10k users.",
        weaknesses: ["Backend ops", "Testing discipline"],
        funfact: "Has a collection of vintage game consoles.",
        contact: "anthony@equipe.com",
        group: "mobile"
    },
    {
        name: "Anthony",
        age: 29,
        location_birth: "Toulouse, France",
        flag: "🇫🇷",
        role: "DevOps Engineer",
        image: "images/antho_bis.png",
        skills: ["CI/CD", "Jenkins", "Terraform", "Linux", "Monitoring"],
        biggest_achivement: "Reduced deployment time from 2 hours to 10 minutes with GitOps.",
        weaknesses: ["Pixel-perfect UI", "Saying no to cool tools"],
        funfact: "Once automated his home with Kubernetes for fun.",
        contact: "anthony@equipe.com",
        group: "devops"
    },
    {
        name: "Badre",
        age: 31,
        location_birth: "Marrakesh, Morocco",
        flag: "🇲🇦",
        role: "Security Analyst",
        image: "images/badre.png",
        skills: ["Pentesting", "SIEM", "Cryptography", "Compliance", "Security Audit"],
        biggest_achivement: "Discovered a critical 0-day in an internal tool and led the fix in 24h.",
        weaknesses: ["Over-paranoia", "UI polish"],
        funfact: "Collects old security conference badges.",
        contact: "badre@equipe.com",
        group: "security"
    },
    {
        name: "Clémentine",
        age: 22,
        location_birth: "Bastia, France",
        flag: "🇫🇷",
        role: "Data Engineer",
        image: "images/clem.png",
        skills: ["Python: I use it almost every day, I think it's the best for data manipulation and analysis.", "SQL : I have a solid understanding of SQL and use it for querying databases.", "Django: I improve a lot my skills in my alternance. They use it for building all their projects."],
        biggest_achivement: "In my alternance, I built a visualization tool to monitor user patterns. This tool helped identify key trends, improved decision-making for the team and fixed some bugs of the backoffice. My team appreciated it and congratulated me for this work.",
        weaknesses: ["Focus : When multitasking, I sometimes struggle to maintain concentration and deliver my best work.", "Don't ask for help : I tend to try to solve problems on my own before reaching out to others, which can lead to unnecessary delays."],
        funfact: "I almost break a production server once, I run tests on it without thinking. But fortunately, it wasn't a big deal because I quickly realized and it was just tests so I fixed it right away.",
        future_plan:"I hope to be hired as a junior data engineer in GoodBarber after my alternance. My team and mentors are very supportive and help me grow my skills every day. They provide valuable feedback and guidance, which I truly appreciate. The multiple projects I work on allow me to learn and improve continuously.",
        contact: "clementine@equipe.com",
        group: "data"
    },
    {
        name: "Dorian",
        age: 27,
        location_birth: "Paris, France",
        flag: "🇫🇷",
        role: "QA Engineer",
        image: "images/dorian.png",
        skills: ["Selenium", "Jest", "Test Automation", "Bug Tracking", "Performance Testing"],
        biggest_achivement: "Introduced contract testing and reduced regressions by 40%.",
        weaknesses: ["Design", "Patience with flaky tests"],
        funfact: "Speedcuber in spare time.",
        contact: "dorian@equipe.com",
        group: "qa"
    },
    {
        name: "Manal",
        age: 24,
        location_birth: "Rabat, Morocco",
        flag: "🇲🇦",
        role: "Digital Marketing",
        image: "images/manal.png",
        skills: ["SEO", "Google Ads", "Social Media", "Analytics", "Content Strategy"],
        biggest_achivement: "Launched a campaign that doubled newsletter signups.",
        weaknesses: ["Technical SEO", "Patience with slow approvals"],
        funfact: "Bakes amazing pistachio cookies.",
        contact: "manal@equipe.com",
        group: "marketing"
    },
    {
        name: "Matthieu",
        age: 30,
        location_birth: "Marseille, France",
        flag: "🇫🇷",
        role: "Solution Architect",
        image: "images/matthieu.png",
        skills: ["Cloud Architecture", "Microservices", "API Design", "Design Patterns", "Scalability"],
        biggest_achivement: "Led the split of a monolith into microservices serving millions of users.",
        weaknesses: ["Pixel design", "Overengineering"],
        funfact: "Built a smart home lab in the garage.",
        contact: "matthieu@equipe.com",
        group: "architecture"
    },
    {
        name: "Mehdi",
        age: 26,
        location_birth: "Tunis, Tunisia",
        flag: "🇹🇳",
        role: "Business Analyst",
        image: "images/med.png",
        skills: ["Requirements Analysis", "Process Modeling", "Stakeholder Management", "Documentation", "Agile BA"],
        biggest_achivement: "Mapped a complex process and cut lead time by 25%.",
        weaknesses: ["SQL depth", "Saying no to scope creep"],
        funfact: "Speaks four languages.",
        contact: "mehdi@equipe.com",
        group: "business"
    },
    {
        name: "Mounia",
        age: 24,
        location_birth: "Casablanca, Morocco",
        flag: "🇲🇦",
        role: "Frontend Developer",
        image: "images/mounia.png",
        skills: ["Vue.js", "TypeScript", "CSS3", "Webpack", "Accessibility"],
        biggest_achivement: "Built a design system used across 5 apps.",
        weaknesses: ["Backend ops", "Unit test coverage"],
        funfact: "Can draw anime portraits.",
        contact: "mounia@equipe.com",
        group: "dev"
    },
    {
        name: "Nicolas",
        age: 29,
        location_birth: "Bordeaux, France",
        flag: "🇫🇷",
        role: "Scrum Master",
        image: "images/nico.png",
        skills: ["Scrum", "Facilitation", "Team Coaching", "Agile Metrics", "Change Management"],
        biggest_achivement: "Scaled agile across 4 squads and improved delivery predictability.",
        weaknesses: ["Deep coding", "Too many retros"],
        funfact: "Runs trail marathons.",
        contact: "nicolas@equipe.com",
        group: "management"
    },
    {
        name: "Stéphane",
        age: 28,
        location_birth: "Montpellier, France",
        flag: "🇫🇷",
        role: "Data Engineer",
        image: "images/ste.png",
        skills: ["Apache Spark", "Data Warehousing", "ETL", "BigQuery", "Data Modeling"],
        biggest_achivement: "Migrated batch ETL to near-real-time with Spark streaming.",
        weaknesses: ["Frontend", "PowerPoint"],
        funfact: "Built a Raspberry Pi cluster for experiments.",
        contact: "stephane@equipe.com",
        group: "data"
    },
    {
        name: "Thomas",
        age: 32,
        location_birth: "Nantes, France",
        flag: "🇫🇷",
        role: "Consultant Tech",
        image: "images/thomas.png",
        skills: ["Digital Strategy", "Tech Advisory", "Innovation", "Workshops", "Roadmapping"],
        biggest_achivement: "Guided a company-wide cloud migration strategy.",
        weaknesses: ["Hands-on coding time", "Too many slides"],
        funfact: "Once organized a 200-person hackathon.",
        contact: "thomas@equipe.com",
        group: "consulting"
    },
    {
        name: "Youssouf",
        age: 27,
        location_birth: "Abidjan, Côte d'Ivoire",
        flag: "🇨🇮",
        role: "UX Researcher",
        image: "images/youssouf.png",
        skills: ["User Research", "Usability Testing", "Personas", "User Journey", "A/B Testing"],
        biggest_achivement: "Redesigned onboarding after a diary study; activation +20%.",
        weaknesses: ["Advanced stats", "Pixel-perfect UI"],
        funfact: "Makes the best bissap in the team.",
        contact: "youssouf@equipe.com",
        group: "design"
    }
];
